apps/blog/urls.py
from django.conf.urls import url
from . import views

app_name = "blog"

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^youcodegirl$', views.youcodegirl, name="youcodegirl"),
    url(r'^fitnessstorypt1$', views.fitnessstorypt1, name="fitnessstorypt1"),
    url(r'^myphotographystory$', views.myphotographystory, name="myphotographystory"),
    # url(r'^join/(?P<id>\d+)$', views.join, name="join"),
    # url(r'^edit/(?P<id>\d+)$', views.edit, name="edit"),
    # url(r'^drop/(?P<id>\d+)$', views.drop, name="drop"),
    # url(r'^remove/(?P<id>\d+)$', views.remove, name="remove"),
    # url(r'^confirm/(?P<id>\d+)$', views.confirm, name="confirm"),

]

apps/website/urls.py
from django.conf.urls import url, include
from . import views

app_name = "website"

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^about$', views.about, name="about"),
    url(r'^photography$', views.photography, name="photography"),
    url(r'^design$', views.design, name="design"),
    url(r'^blog$', views.blog, name="blog"),
    url(r'^contact$', views.contact, name="contact"),
]

thejennuinelife/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^blog/', include('apps.blog.urls', namespace="blog")),
    url(r'^', include('apps.website.urls', namespace="website")),

]

apps/blog/models.py
from __future__ import unicode_literals
from django.db import models

class  Blog(models.Model):
    title = models.CharField(max_length=100)
    category = models.CharField(max_length=100)
    entry = models.TextField(max_length = 4000)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

apps/website/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/blog/views.py
from django.shortcuts import render
from . models import Blog

def index(request):

    return render(request, 'blog/index.html')


def youcodegirl(request):

    return render(request, 'blog/posts/thegrind/youcodegirl.html')

def myphotographystory(request):

    return render(request, 'blog/posts/thegrind/myphotographystory.html')


def fitnessstorypt1(request):

    return render(request, 'blog/posts/thegrind/fitnessstorypt1.html')

apps/website/views.py
from django.shortcuts import render, HttpResponse


def index(request):

    return render(request, 'website/index.html')

def about(request):

    return render(request, 'website/about.html')


def photography(request):

    return render(request, 'website/photography.html')


def design(request):

    return render(request, 'website/design.html')

def blog(request):

    return render(request, 'blog/index.html')

def contact(request):

    return render(request, 'website/contact.html')

apps/blog/templates/blog/confirm.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Confirm</title>
        {% load static %}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.css">
        <link rel="stylesheet" href="{% static 'courses/css/style.css' %}">
    </head>
    <body>
        Course has been deleted!
        <form action="{% url 'courses:index '%}" method="post">
            {% csrf_token %}
            <input type="submit" value="Return Home">
        </form>
    </body>
</html>

apps/blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="The Jennuine Life is the hub of all things Jennifer Cortes, a freelance web designer amp&; lifestyle photographer and blogger based out of Frisco, TX. The Jennuine Life is a way for me to share not only my design and photography work, but my love for fitness, food, travel, reading, and the genuine life I live.">
	<meta name="author" content="Jennifer Cortes">
	<meta name="keywords" content="photographer, web designer, graphic designer, freelancer, lifestyle, blog, blogger, foodie, fitness, health, jennuinelife, photography, portraits, developer, coder">
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-84824412-1', 'auto');
	  ga('send', 'pageview');

	</script>

	<title>The Jennuine Life | Blog</title>
	{% load static %}
	<!-- Bootstrap core CSS -->
	<link rel="shortcut icon" href="{% static 'favicon/favicon.ico' %}"/>
	<link rel="stylesheet" href="{% static 'website/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'website/css/simpletextrotator.css' %}">
	<link rel="stylesheet" href="{% static 'website/css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'website/css/et-line-font.css' %}">
	<link rel="stylesheet" href="{% static 'website/css/magnific-popup.css' %}">
	<link rel="stylesheet" href="{% static 'website/css/flexslider.css' %}">
	<link rel="stylesheet" href="{% static 'website/css/animate.css' %}">
	<link rel="stylesheet" href="{% static 'website/css/style.css' %}">
	<link rel="stylesheet" href="{% static 'website/css/custom.css' %}">


</head>
<body>

	<!-- PRELOADER -->
	<div class="page-loader">
		<div class="loader">Loading...</div>
	</div>

	<!-- /PRELOADER -->

	<!-- NAVIGATION -->
	<nav class="navbar navbar-custom navbar-transparent navbar-fixed-top" >

			<div class="container">

				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#custom-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="{% url 'website:index'%}">The Jennuine Life</a>
				</div>

				<div class="collapse navbar-collapse" id="custom-collapse">

					<ul class="nav navbar-nav navbar-right">

						<li>
						<a href="{% url 'website:index'%}">Home</a>
						</li>
						<li>
							<a href="{% url 'website:about'%}">About</a>
						</li>
						<li class="dropdown">
							<a href="" class="dropdown-toggle" data-toggle="dropdown">Portfolio</a>
							<ul class="dropdown-menu" role="menu">
								<li>
									<a href="{% url 'website:photography'%}">Photography</a>
								</li>
								<li>
									<a href="{% url 'website:design'%}">Web &amp; Branding</a>
								</li>
							</ul>
						</li>
						<li>
							<a href="{% url 'blog:index'%}">Blog</a>
						</li>
						<li>
							<a href="{% url 'website:contact'%}">Contact</a>
						</li>

					</ul>
				</div>

			</div>

	</nav>
	<!-- /NAVIGATION -->


	<div class="module module-header bg-dark bg-dark-50" data-background="{% static 'website/images/blog.jpg' %}">
		<div class="hs-caption container">
			<div class="caption-content">
				<div class="hs-title-size-4 font-alt m-b-30">
					Le Blog
				</div>
			</div>
		</div>
	</div  >
	<!-- /HOME -->

	<!-- WRAPPER -->
	<br>
	<br>
	<div class="wrapper">
		<!-- PORTFOLIO -->

	<div class="module-small portfolio_area p-b-60">
		<div class="container">
			<!-- PORTFOLIO FILTER -->
			<div class="row">
				<div class="col-sm-12">
					<ul id="filters" class="filter font-inc">
						<li><a href="#" data-filter="*" class="current wow fadeInUp">All</a></li>
						<li><a href="#" data-filter=".lifestyle" class="wow fadeInUp" data-wow-delay="0.2s">Lifestyle</a></li>
						<li><a href="#" data-filter=".fitness" class="wow fadeInUp" data-wow-delay="0.4s">Fitness &amp; Nutrition</a></li>
						<li><a href="#" data-filter=".work" class="wow fadeInUp" data-wow-delay="0.6s">The Grind</a></li>
						<li><a href="#" data-filter=".other" class="wow fadeInUp" data-wow-delay="0.8s">Other</a></li>
					</ul>

				</div>
			</div>
		</div>
			<!-- /PORTFOLIO FILTER -->

			<!-- PORTFOLIO LIST -->
			<div class="container">
				<div class="row">
					<div class="col-xs-12 col-xs-12 col-md-12">
						<ul id="works-grid" class="works-grid works-grid-gut works-grid-3 works-hover-w">

							<!-- PORTFOLIO ITEM -->
							<li class="work-item illustration fitness">
								<a href="{% url 'blog:fitnessstorypt1'%}">
									<div class="post">
										<div class="post-thumbnail">
												<a href="{% url 'blog:fitnessstorypt1'%}"><img src="{% static 'website/images/posts/fitness/sneakers.jpg' %}"></a>
										</div>
										<div class="post-header">
											<h2 class="post-title font-alt"><a href="{% url 'blog:fitnessstorypt1'%}">My Fitness Story | Pt 1</a></h2>
											<div class="post-meta font-inc">
												By <a href="{% url 'website:about'%}">Jennifer Cortes</a> | APRIL 1 2017
											</div>
										</div>
										<div class="post-entry">
											<p>It wasn't an epic, exciting, or Hallmark worthy start...it all started with me waking up one morning and not being able to remember when the last time was that I had broken a sweat or the last time I had gone a day without cheesy fiesta potatoes from Taco Bell...</p>
										</div>
										<div class="post-more font-inc">
											<a href="{% url 'blog:fitnessstorypt1'%}" class="more-link">Read more</a>

										</div>
									</div>
								</a>
							</li>
							<!-- /PORTFOLIO ITEM -->

							<!-- PORTFOLIO ITEM -->
							<li class="work-item illustration lifestyle">
								<a href="posts/thegrind/myphotographystory">
									<div class="post">
										<div class="post-thumbnail">
											<a href="{% url 'blog:myphotographystory'%}"><img src="{% static 'website/images/posts/thegrind/photography.jpg' %}"></a>
										</div>
										<div class="post-header">
											<h2 class="post-title font-alt"><a href="{% url 'blog:myphotographystory'%}">My Photography Story</a></h2>
											<div class="post-meta font-inc">
												By <a href="#">Jennifer Cortes</a> | APRIL 1 2017
											</div>
										</div>
										<div class="post-entry">
											<p>Becoming a “photographer” happened by accident. It wasn’t something that I always had a passion for or dreamed of doing…it was something that happened to fall into my lap one evening and ended up turning into more...</p>
										</div>
										<div class="post-more font-inc">
											<a href="{% url 'blog:myphotographystory'%}" class="more-link">Read more</a>
										</div>
									</div>
								</a>
							</li>
							<!-- /PORTFOLIO ITEM -->

							<!-- PORTFOLIO ITEM -->
							<li class="work-item illustration work">
								<a href="posts/thegrind/youcodegirl">
									<div class="post">
										<div class="post-thumbnail">
										<a href="{% url 'blog:youcodegirl'%}"><img src="{% static 'website/images/posts/thegrind/coding.jpg' %}"></a>
										</div>
										<div class="post-header">
											<h2 class="post-title font-alt"><a href="{% url 'blog:youcodegirl'%}">You Code, Girl!</a></h2>
											<div class="post-meta font-inc">
												By <a href="{% url 'website:about'%}">Jennifer Cortes</a> | APRIL 1 2017
											</div>
										</div>
										<div class="post-entry">
											<p>I remember the first time I saw someone coding. My first thought was "uh, that looks hella boring" and my second thought was "wtf does all of that mean?".  Flash forward 5 years and here I am, thinking code is the titties, and telling you to start too.</p>
										</div>
										<div class="post-more font-inc">
											<a href="{% url 'blog:youcodegirl'%}" class="more-link">Read more</a>
										</div>
									</div>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>


		<!-- DIVIDER -->
		<hr class="divider-w">
		<!-- /DIVIDER -->

		<!-- CONTACT -->
		<br>
		<div class="row">
			<div class="col-lg-12 text-center">
				<h2 class="module-title align-center font-alt">Check out my IG</h2>
				<script src="https://snapwidget.com/js/snapwidget.js"></script>
				<iframe src="https://snapwidget.com/embed/361632" class="snapwidget-widget" allowTransparency="true" frameborder="0" scrolling="no" style="border:none; overflow:hidden; width:100%; "></iframe>
			</div>
		</div>

		<!-- /CONTACT -->
		<!-- FOOTER -->
	<footer class="footer">
		<div class="container">
			<div class="row">
				<div class="col-sm-12 text-center">
					<p class="copyright font-inc m-b-0">© 2017 <a href="{% url 'website:index'%}">The Jennuine Life</a>, All Rights Reserved.</p>
				</div>
				<div class="row">
					<div class="col-sm-12">
						<div class="content-box">
							<div class="content-box-icon">
								<a href="http://www.facebook.com/thejennuinelife" target="blank"><img src="{% static 'website/images/fb.png' %}" width="40px"/></a>
								<a href="http://www.instagram.com/thejennuinelife" target="blank"><img src="{% static 'website/images/ig.png' %}" width="40px"/></a>
								<a href="http://www.twitter.com/thejennuinelife" target="blank"><img src="{% static 'website/images/twitter.png' %}" width="40px"/></a> Des
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</footer>

	<!-- /WRAPPER -->

	<!-- Scroll-up -->
	<div class="scroll-up">
		<a href="#totop"><i class="fa fa-angle-double-up"></i></a>
	</div>

	<!-- Javascript files -->
	<script src="{% static 'website/js/jquery-2.2.4.min.js' %}"></script>
	<script src="{% static 'website/bootstrap/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'website/js/appear.js' %}"></script>
	<script src="{% static 'website/js/jquery.simple-text-rotator.min.js' %}"></script>
	<script src="{% static 'website/js/jqBootstrapValidation.js' %}"></script>
	<script src="{% static 'website/js/isotope.pkgd.min.js' %}"></script>
	<script src="{% static 'website/js/imagesloaded.pkgd.js' %}"></script>
	<script src="{% static 'website/js/jquery.flexslider-min.js' %}"></script>
	<script src="{% static 'website/js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'website/js/jquery.fitvids.js' %}"></script>
	<script src="{% static 'website/js/smoothscroll.js' %}"></script>
	<script src="{% static 'website/js/smoothscroll.js' %}"></script>
	<script src="{% static 'website/js/wow.min.js' %}"></script>
	<script src="{% static 'website/js/smoothscroll.js' %}"></script>
	<script src="{% static 'website/js/contact.js' %}"></script>
	<script src="{% static 'website/js/smoothscroll.js' %}"></script>
	<script src="{% static 'website/js/custom.js' %}"></script>
	</body>

	</html>

apps/blog/templates/blog/posts/thegrind/myphotographystory.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="The Jennuine Life is the hub of all things Jennifer Cortes, a freelance web designer amp&; lifestyle photographer and blogger based out of Frisco, TX. The Jennuine Life is a way for me to share not only my design and photography work, but my love for fitness, food, travel, reading, and the genuine life I live.">
	<meta name="author" content="Jennifer Cortes">
	<meta name="keywords" content="photographer, web designer, graphic designer, freelancer, lifestyle, blog, blogger, foodie, fitness, health, jennuinelife, photography, portraits, developer, coder">

	<title>The Jennuine Life | Blog</title>
	{% load static %}
	<!-- Bootstrap core CSS -->
	<link rel="shortcut icon" href="{% static 'favicon/favicon.ico' %}"/>
	<link rel="stylesheet" href="{% static 'website/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'website/css/simpletextrotator.css' %}">
	<link rel="stylesheet" href="{% static 'website/css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'website/css/et-line-font.css' %}">
	<link rel="stylesheet" href="{% static 'website/css/magnific-popup.css' %}">
	<link rel="stylesheet" href="{% static 'website/css/flexslider.css' %}">
	<link rel="stylesheet" href="{% static 'website/css/animate.css' %}">
	<link rel="stylesheet" href="{% static 'website/css/style.css' %}">
	<link rel="stylesheet" href="{% static 'website/css/custom.css' %}">


</head>
<body>

	<!-- PRELOADER -->
	<div class="page-loader">
		<div class="loader">Loading...</div>
	</div>
	<!-- /PRELOADER -->

	<!-- NAVIGATION -->
	<nav class="navbar navbar-custom navbar-transparent navbar-fixed-top" >

			<div class="container">

				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#custom-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="{% url 'website:index'%}">The Jennuine Life</a>
				</div>

				<div class="collapse navbar-collapse" id="custom-collapse">

					<ul class="nav navbar-nav navbar-right">

						<li>
						<a href="{% url 'website:index'%}">Home</a>
						</li>
						<li>
							<a href="{% url 'website:about'%}">About</a>
						</li>
						<li class="dropdown">
							<a href="" class="dropdown-toggle" data-toggle="dropdown">Portfolio</a>
							<ul class="dropdown-menu" role="menu">
								<li>
									<a href="{% url 'website:photography'%}">Photography</a>
								</li>
								<li>
									<a href="{% url 'website:design'%}">Web &amp; Branding</a>
								</li>
							</ul>
						</li>
						<li>
							<a href="{% url 'blog:index'%}">Blog</a>
						</li>
						<li>
							<a href="{% url 'website:contact'%}">Contact</a>
						</li>

					</ul>
				</div>

			</div>

	</nav>
	<!-- /NAVIGATION -->

	<!-- WRAPPER -->
	<div class="wrapper">

		<!-- HOME -->
		<div class="module module-header bg-dark bg-dark-50" data-background="assets/images/.jpg">

			<div class="container">

				<!-- MODULE TITLE -->
				<div class="row">

					<div class="col-sm-8 col-sm-offset-2">

						<h1 class="module-title font-alt align-center">My Photography Story</h1>



					</div>

				</div>
				<!-- /MODULE TITLE -->

			</div>

		</div  >
		<!-- /HOME -->

		<!-- BLOG SINGLE -->
		<div class="module-small pdd-88-n">

			<div class="container">

				<div class="row">

					<div class="col-sm-8 col-sm-offset-2">

						<!-- POST -->
						<div class="post">

							<div class="post-thumbnail">
								<a href="{% url 'blog:myphotographystory'%}"><img src="{% static 'website/images/posts/thegrind/photography.jpg' %}"></a>
							</div>

							<div class="post-entry">

								<p>Becoming a “photographer” (I still don’t feel comfortable calling myself that) happened by accident. It wasn’t something that I always had a passion for or dreamed of doing…it was something that happened to fall into my lap one evening and ended up turning into more.</p>

								<p>In high school, I was both in Newspaper and in Yearbook. In Yearbook, I was mostly in charge of layout design and in Newspaper, writing content (with the occasional anchor role for a supppperrr cheesy and now looking back, HILARIOUS news segment we had.) One day, the person that was in charge of doing photos for a volleyball game for Newspaper couldn’t make it, so I had to fill in. I was handed a Nikon d3000 and off I went to capture a game that I would have typically just been a spectator for. I don’t remember how the pictures turned out (Probably SUPER crappy), but I do remember the feeling of capturing the pictures, and because of that, I volunteered to be the designated picture taker.</p>

								<p>The teacher we had for Newspaper, Coach Shifflet, played a HUGE role in me taking up photography. Not only did he allow me to document images for the paper, but he would let me check out the camera after school so that I could drive around the backroads of my tiny-ass town, taking pictures of anything and everything. Mostly crap that people had in their yards.</p>

								<p>I didn’t take portraits (pictures of an actual human being) until a few months later…it was of one my friends, Halie, who was so pretty that I knew that even if I did a terrible job taking the photos, she would redeem me. So off we went to our neighboring town and I took my first set of portraits.</p>

								<div class="row">

									<div class="col-sm-6 col-md-6 col-lg-6">
										<img src="{% static 'website/images/posts/thegrind/halie3.png' %}">
									</div>
									<div class="col-sm-6 col-md-6 col-lg-6">
										<img src="{% static 'website/images/posts/thegrind/halie2.png' %}">
									</div>
								</div>
								<div class="row">
									<div class="col-sm-12 col-md-12 col-lg-12">
										<img src="{% static 'website/images/posts/thegrind/halie1.png' %}">
									</div>
								</div>
								<div class="row">

									<div class="col-sm-12 col-md-12 col-lg-12">
										<center><i>My first set of portraits | Fall 2009</i></center>
									</div>

								</div>
								<br>
								<br>
								<p>From there I began posting pictures of what I took, my friends started talking about it, and through word of mouth, people began asking to have their pictures taken. I was about to graduate high school though, which meant that I would be out of a camera. And this is where once again, Coach Shifflet came in…he made it possible for me to get my own Nikon d3000. I busted my ass that summer to repay him for the camera, but to this day, I don’t know how I will repay him for the jump start he gave me into something that now largely defines me. Shiffy, if you’re reading this…you know how much I value what is now a friendship, how much I look up to you, and I hope you know how eternally grateful I am to you.</p>

								<p>Anyways, I continued to take pictures of everything I could, no matter how random, and to buy photography books, watch videos, and basically teach myself everything I could. I eventually upgraded my camera to Luna, the d700 that I have now, and continued to teach myself what shutter speed, composition, aperture, white balance, ISO, and countless other things meant.</p>

								<p>In 2012, I launched Jennuine Photos. It was when I became “official” and got a FB page, website, business cards, tax id, etc. Every year since then, I have grown as a camera wielder, not only by continuing to learn about this craft and industry, but by being blessed to have photographed countless individuals, families, couples, etc. </p>

								<p>I have loved looking back at my first first images and then looking at my current ones and seeing how I have evolved and how with each passing year, I see more of myself in the images I take. From the way I photograph to the way I edit, each passing year my images have become more and more me.
								<div class="row">

									<div class="col-sm-6 col-md-6 col-lg-6">
										<img src="{% static 'website/images/posts/thegrind/bri1.jpg' %}">
									</div>
									<div class="col-sm-6 col-md-6 col-lg-6">
										<img src="{% static 'website/images/posts/thegrind/bri2.jpg' %}">
									</div>
								</div>
								<div class="row">
									<div class="col-sm-12 col-md-12 col-lg-12">
										<img src="{% static 'website/images/posts/thegrind/bri3.jpg' %}">
									</div>
								</div>
								<div class="row">

									<div class="col-sm-12 col-md-12 col-lg-12">
										<center><i>My most recent session | March 2017</i></center>
									</div>

								</div>
								<br>
								<br>
								<p>I have learned something valuable from each and every session I have done and this year, as Jennuine Photos became part of The Jennuine Life, I look forward to continuing to continuing to grow and improve what I can do with this camera of mine.</p>

								<p>To those that have supported me and my journey in this area of my genuine life, I thank you from the bottom of my heart. It has been a wonderful 5 official  years and I wouldn’t have been able to do it without you. Whether you rooted for me, booked me, referred me, liked my images on FB…you made this humble photography business happen just as much as me and my camera did.</p>
								<br>

								<p><i>I am not a full time photographer, as this is not my career path. I consider myself a dedicated hobby-ist and am so grateful to have people who seek me to capture their stories. If you're interested in having photos taken, simply head over to the contact page and drop me a line! </i></p>

								<center><h3>Okay Baiiii,<br>
										Jenn</h3></center>



							</div>
						</div>
					</div>
				</div>
			</div>
		</div >
		<!-- /BLOG SINGLE -->

		<!-- DIVIDER -->
		<hr class="divider-w">
		<!-- /DIVIDER -->

		<!-- CONTACT -->
		<div class="module-small">
				<div class="row">
					<div class="col-lg-12 text-center">
						<h2 class="module-title align-center font-alt">Check out my IG</h2>
						<script src="https://snapwidget.com/js/snapwidget.js"></script>
						<iframe src="https://snapwidget.com/embed/361632" class="snapwidget-widget" allowTransparency="true" frameborder="0" scrolling="no" style="border:none; overflow:hidden; width:100%; "></iframe>
					</div>
			</div>

		</div >
		<!-- /CONTACT -->
		<!-- FOOTER -->
		<footer class="footer">

			<div class="container">

				<div class="row">

					<div class="col-sm-12 text-center">
						<p class="copyright font-inc m-b-0">© 2017 <a href="index.html">The Jennuine Life</a>, All Rights Reserved.</p>
					</div>
					<div class="row">
						<div class="col-sm-12">
							<div class="content-box">
								<div class="content-box-icon">
									<a href="http://www.facebook.com/thejennuinelife" target="blank"><img src="{% static 'website/images/fb.png' %}" width="40px"/></a>
									<a href="http://www.instagram.com/thejennuinelife" target="blank"><img src="{% static 'website/images/ig.png' %}" width="40px"/></a>
									<a href="http://www.twitter.com/thejennuinelife" target="blank"><img src="{% static 'website/images/twitter.png' %}" width="40px"/></a>


								</div>

							</div>
						</div>
					</div>

				</div>

			</div>

		</footer>

	</div>
	<!-- /WRAPPER -->

	<!-- Scroll-up -->
	<div class="scroll-up">
		<a href="#totop"><i class="fa fa-angle-double-up"></i></a>
	</div>

	<!-- Javascript files -->
	<script src="{% static 'website/js/jquery-2.2.4.min.js' %}"></script>
	<script src="{% static 'website/bootstrap/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'website/js/appear.js' %}"></script>
	<script src="{% static 'website/js/jquery.simple-text-rotator.min.js' %}"></script>
	<script src="{% static 'website/js/jqBootstrapValidation.js' %}"></script>
	<script src="{% static 'website/js/isotope.pkgd.min.js' %}"></script>
	<script src="{% static 'website/js/imagesloaded.pkgd.js' %}"></script>
	<script src="{% static 'website/js/jquery.flexslider-min.js' %}"></script>
	<script src="{% static 'website/js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'website/js/jquery.fitvids.js' %}"></script>
	<script src="{% static 'website/js/smoothscroll.js' %}"></script>
	<script src="{% static 'website/js/smoothscroll.js' %}"></script>
	<script src="{% static 'website/js/wow.min.js' %}"></script>
	<script src="{% static 'website/js/smoothscroll.js' %}"></script>
	<script src="{% static 'website/js/contact.js' %}"></script>
	<script src="{% static 'website/js/smoothscroll.js' %}"></script>
	<script src="{% static 'website/js/custom.js' %}"></script>
	</body>

	</html>